---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuguozhu.
--- DateTime: 2019-07-14 22:23
---

file = io.input("/Users/liuguozhu/workspace/lua-learning/src/test_date.lua")

repeat
    line = io.read()
    if nil == line then
        break
    end

    print(line)


until (false)

io.close(file)