---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuguozhu.
--- DateTime: 2019-07-14 22:23
---

print(os.time())

a = { year = 2019, month = 7, day = 14, hour = 22, min = 25 }
print(os.time(a))

local day1 = { year = 2015, month = 7, day = 30 }
local t1 = os.time(day1)

local day2 = { year = 2015, month = 7, day = 31 }
local t2 = os.time(day2)
print(os.difftime(t2, t1))   -->output  86400